<?php
/**
 * api/lib/email_templates.php
 * ───────────────────────────
 * Renders branded HTML email bodies for subscription lifecycle events.
 *
 * Every template returns an array: ['subject' => string, 'html' => string].
 * Plain-text alternatives are auto-generated by the mailer from the HTML.
 *
 * All user-supplied values are HTML-escaped to prevent injection into the
 * rendered message.
 */

declare(strict_types=1);

/** Human-friendly plan label + price map (kept in sync with the admin UI). */
function planLabel(?string $plan): string
{
    return match ($plan) {
        'weekly'  => 'Weekly',
        'monthly' => 'Monthly',
        'trial'   => 'Trial',
        default   => '—',
    };
}

/** Billing amount (USD) for a plan. Returns a display string. */
function planPrice(?string $plan): string
{
    return match ($plan) {
        'weekly'  => '$9.99',
        'monthly' => '$29.99',
        'trial'   => '$0.00',
        default   => '—',
    };
}

/** Format a datetime string for display, or an em dash when null. */
function fmtDate(?string $dt): string
{
    if ($dt === null || $dt === '') {
        return '—';
    }
    $ts = strtotime($dt);
    return $ts ? date('D, d M Y', $ts) : '—';
}

/** Wrap inner content in the shared responsive email shell. */
function emailLayout(string $title, string $innerHtml): string
{
    $brand    = htmlspecialchars(env('MAIL_FROM_NAME', 'IT Guru Trading'), ENT_QUOTES, 'UTF-8');
    $appUrl   = htmlspecialchars(env('APP_URL', env('AUTH_API_BASE', '')), ENT_QUOTES, 'UTF-8');
    $safeTitle = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
    $year     = date('Y');

    return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0e1116;font-family:Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#e6e6e6;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#0e1116;padding:24px 0;">
    <tr><td align="center">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#161b22;border:1px solid #232a33;border-radius:12px;overflow:hidden;">
        <tr><td style="background:#1f6feb;padding:20px 28px;color:#fff;font-size:18px;font-weight:700;">{$brand}</td></tr>
        <tr><td style="padding:28px;">
          <h1 style="margin:0 0 16px;font-size:20px;color:#fff;">{$safeTitle}</h1>
          {$innerHtml}
        </td></tr>
        <tr><td style="padding:18px 28px;border-top:1px solid #232a33;font-size:12px;color:#8b949e;">
          <p style="margin:0 0 6px;">This is an automated message from {$brand}.</p>
          <p style="margin:0;">&copy; {$year} {$brand}. Trading involves risk. Past performance is not indicative of future results.</p>
          <p style="margin:8px 0 0;"><a href="{$appUrl}" style="color:#58a6ff;">Manage your subscription</a></p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>
HTML;
}

/** Render the subscription-details card shared across templates. */
function subscriptionDetailsCard(array $d): string
{
    $rows = [
        ['Plan',          planLabel($d['plan'] ?? null)],
        ['Billing amount', $d['amount'] ?? planPrice($d['plan'] ?? null)],
        ['Renewal date',  fmtDate($d['expires_at'] ?? null)],
        ['Status',        ucfirst((string) ($d['status'] ?? 'inactive'))],
    ];
    $html = '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
          . 'style="margin:8px 0 20px;border-collapse:collapse;">';
    foreach ($rows as [$label, $value]) {
        $l = htmlspecialchars((string) $label, ENT_QUOTES, 'UTF-8');
        $v = htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
        $html .= "<tr>"
              . "<td style=\"padding:8px 0;color:#8b949e;font-size:14px;width:45%;\">$l</td>"
              . "<td style=\"padding:8px 0;color:#fff;font-size:14px;font-weight:600;\">$v</td>"
              . "</tr>";
    }
    $html .= '</table>';
    return $html;
}

/**
 * Subscription change notification (upgrade / downgrade / status change / renewal).
 *
 * @param array $d name, plan, status, expires_at, amount, change (string label)
 * @return array{subject:string,html:string}
 */
function tplSubscriptionChanged(array $d): array
{
    $name   = htmlspecialchars((string) ($d['name'] ?? 'there'), ENT_QUOTES, 'UTF-8');
    $change = (string) ($d['change'] ?? 'updated');

    $headline = match ($change) {
        'upgrade'   => 'Your plan has been upgraded 🎉',
        'downgrade' => 'Your plan has been changed',
        'renewal'   => 'Your subscription renewed successfully ✅',
        'activated' => 'Your subscription is now active ✅',
        'status'    => 'Your subscription status changed',
        default     => 'Your subscription was updated',
    };

    $intro = match ($change) {
        'upgrade'   => "Great news — your subscription has been upgraded. Here are your new plan details:",
        'downgrade' => "Your subscription plan has been changed. Here are your updated details:",
        'renewal'   => "Thank you! Your subscription has been renewed. Here are the details:",
        'activated' => "Your subscription is now active and you have full access. Details below:",
        'status'    => "Your subscription status has changed. Here are the current details:",
        default     => "Your subscription details have been updated:",
    };

    $inner = "<p style=\"margin:0 0 12px;font-size:15px;\">Hi {$name},</p>"
           . "<p style=\"margin:0 0 8px;font-size:15px;color:#c9d1d9;\">{$intro}</p>"
           . subscriptionDetailsCard($d)
           . "<a href=\"" . htmlspecialchars(env('APP_URL', ''), ENT_QUOTES, 'UTF-8') . "\" "
           . "style=\"display:inline-block;background:#1f6feb;color:#fff;text-decoration:none;padding:10px 20px;border-radius:8px;font-size:14px;\">Open dashboard</a>";

    return ['subject' => $headline, 'html' => emailLayout($headline, $inner)];
}

/**
 * Upcoming-expiry reminder.
 *
 * @param array $d name, plan, status, expires_at, amount, days_before
 * @return array{subject:string,html:string}
 */
function tplExpiryReminder(array $d): array
{
    $name = htmlspecialchars((string) ($d['name'] ?? 'there'), ENT_QUOTES, 'UTF-8');
    $days = (int) ($d['days_before'] ?? 0);
    $dayWord = $days === 1 ? 'tomorrow' : "in {$days} days";

    $subject = "Your subscription expires {$dayWord}";
    $inner = "<p style=\"margin:0 0 12px;font-size:15px;\">Hi {$name},</p>"
           . "<p style=\"margin:0 0 8px;font-size:15px;color:#c9d1d9;\">This is a friendly reminder that your subscription will expire <strong>{$dayWord}</strong>. Renew now to keep uninterrupted access to signals and the private trading group.</p>"
           . subscriptionDetailsCard($d)
           . "<a href=\"" . htmlspecialchars(env('APP_URL', ''), ENT_QUOTES, 'UTF-8') . "\" "
           . "style=\"display:inline-block;background:#1f6feb;color:#fff;text-decoration:none;padding:10px 20px;border-radius:8px;font-size:14px;\">Renew subscription</a>";

    return ['subject' => $subject, 'html' => emailLayout($subject, $inner)];
}

/**
 * Subscription expired notice.
 *
 * @param array $d name, plan, status, expires_at
 * @return array{subject:string,html:string}
 */
function tplSubscriptionExpired(array $d): array
{
    $name = htmlspecialchars((string) ($d['name'] ?? 'there'), ENT_QUOTES, 'UTF-8');
    $subject = 'Your subscription has expired';

    $inner = "<p style=\"margin:0 0 12px;font-size:15px;\">Hi {$name},</p>"
           . "<p style=\"margin:0 0 8px;font-size:15px;color:#c9d1d9;\">Your subscription has expired and access to premium features and the private trading group has been paused. Renew any time to instantly restore full access.</p>"
           . subscriptionDetailsCard($d)
           . "<a href=\"" . htmlspecialchars(env('APP_URL', ''), ENT_QUOTES, 'UTF-8') . "\" "
           . "style=\"display:inline-block;background:#238636;color:#fff;text-decoration:none;padding:10px 20px;border-radius:8px;font-size:14px;\">Renew &amp; restore access</a>";

    return ['subject' => $subject, 'html' => emailLayout($subject, $inner)];
}
